version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  api_key:
    secure: CFF9dh7xUuj8qHYqx3BV5w4xWPtxlwTMlPD2x7Dz+95x0DVKh98bVBsghhKktilE
build_script:
- ps: >-
    dotnet restore

    $xmlPath = "$env:appveyor_build_folder\src\Boomer\Boomer.csproj"

    $xml = [xml](get-content $xmlPath)

    $propertyGroup = $xml.Project.PropertyGroup

    $propertyGroup.Version = $env:appveyor_build_version

    $xml.Save($xmlPath)

    dotnet build -c Release
on_success:
- ps: >-
    if(!$env:APPVEYOR_PULL_REQUEST_NUMBER)
    {
        nuget.exe setApiKey $env:api_key -source https://www.nuget.org
        nuget push "$env:appveyor_build_folder\src\Boomer\bin\Release\Boomer.$env:appveyor_build_version.nupkg" -source https://www.nuget.org/api/v2/package
    }